[package]
name = "imagemanip"
version = "0.2.0"
authors = ["John Kossa <kg959ster@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
gif = "0.11.1"
rayon = "1.5.0"